/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SoundChatRouteImport } from './routes/sound-chat'
import { Route as RRoomIdRouteImport } from './routes/r.$roomId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SoundChatRoute = SoundChatRouteImport.update({
  id: '/sound-chat',
  path: '/sound-chat',
  getParentRoute: () => rootRouteImport,
} as any)
const RRoomIdRoute = RRoomIdRouteImport.update({
  id: '/r/$roomId',
  path: '/r/$roomId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sound-chat': typeof SoundChatRoute
  '/r/$roomId': typeof RRoomIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sound-chat': typeof SoundChatRoute
  '/r/$roomId': typeof RRoomIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sound-chat': typeof SoundChatRoute
  '/r/$roomId': typeof RRoomIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/sound-chat' | '/r/$roomId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/sound-chat' | '/r/$roomId'
  id: '__root__' | '/' | '/sound-chat' | '/r/$roomId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SoundChatRoute: typeof SoundChatRoute
  RRoomIdRoute: typeof RRoomIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sound-chat': {
      id: '/sound-chat'
      path: '/sound-chat'
      fullPath: '/sound-chat'
      preLoaderRoute: typeof SoundChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/r/$roomId': {
      id: '/r/$roomId'
      path: '/r/$roomId'
      fullPath: '/r/$roomId'
      preLoaderRoute: typeof RRoomIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SoundChatRoute: SoundChatRoute,
  RRoomIdRoute: RRoomIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
